
# ******************************************
def make_state_codes():
    codes = {
        "AL": "01", 
        "AK": "02", 
        "AZ": "04", 
        "AR": "05", 
        "CA": "06", 
        "CO": "08", 
        "CT": "09", 
        "DE": "10", 
  	    "DC": "11", 
        "FL": "12", 
        "GA": "13", 
        "HI": "15", 
        "ID": "16", 
        "IL": "17", 
        "IN": "18", 
        "IA": "19", 
        "KS": "20", 
        "KY": "21", 
        "LA": "22", 
        "ME": "23", 
        "MD": "24", 
        "MA": "25", 
        "MI": "26", 
        "MN": "27", 
        "MS": "28", 
        "MO": "29", 
        "MT": "30", 
        "NE": "31", 
        "NV": "32", 
        "NH": "33", 
        "NJ": "34", 
        "NM": "35", 
        "NY": "36", 
        "NC": "37", 
        "ND": "38", 
        "OH": "39", 
        "OK": "40", 
        "OR": "41", 
        "PA": "42", 
        "RI": "44", 
        "SC": "45", 
        "SD": "46", 
        "TN": "47", 
        "TX": "48", 
        "UT": "49", 
        "VT": "50", 
        "VA": "51", 
        "WA": "53", 
        "WV": "54", 
        "WI": "55", 
        "WY": "56"} 
    return codes

def make_state_names():
    names = {
        "AL": "Alabama", 
        "AK": "Alaska", 
        "AZ": "Arizona", 
        "AR": "Arkansas", 
        "CA": "California", 
        "CO": "Colorado", 
        "CT": "Connecticut", 
        "DE": "Delaware", 
  	    "DC": "District of Columbia", 
        "FL": "Florida", 
        "GA": "Georgia", 
        "HI": "Hawaii", 
        "ID": "Idaho", 
        "IL": "Illinois", 
        "IN": "Indiana", 
        "IA": "Iowa", 
        "KS": "Kansas", 
        "KY": "Kentucky", 
        "LA": "Louisiana", 
        "ME": "Maine", 
        "MD": "Maryland", 
        "MA": "Massachusetts", 
        "MI": "Michigan", 
        "MN": "Minnesota", 
        "MS": "Mississippi", 
        "MO": "Missouri", 
        "MT": "Montana", 
        "NE": "Nebraska", 
        "NV": "Nevada", 
        "NH": "New Hampshire", 
        "NJ": "New Jersey", 
        "NM": "New Mexico", 
        "NY": "New York", 
        "NC": "North Carolina", 
        "ND": "North Dakota", 
        "OH": "Ohio", 
        "OK": "Oklahoma", 
        "OR": "Oregon", 
        "PA": "Pennsylvania", 
        "RI": "Rhode Island", 
        "SC": "South Carolina", 
        "SD": "South Dakota", 
        "TN": "Tennessee", 
        "TX": "Texas", 
        "UT": "Utah", 
        "VT": "Vermont", 
        "VA": "Virginia", 
        "WA": "Washington", 
        "WV": "West Virginia", 
        "WI": "Wisconsin", 
        "WY": "Wyoming"} 
    return names

def make_state_names_nospace():
    names = {
        "AL": "Alabama", 
        "AK": "Alaska", 
        "AZ": "Arizona", 
        "AR": "Arkansas", 
        "CA": "California", 
        "CO": "Colorado", 
        "CT": "Connecticut", 
        "DE": "Delaware", 
  	    "DC": "DistrictOfColumbia", 
        "FL": "Florida", 
        "GA": "Georgia", 
        "HI": "Hawaii", 
        "ID": "Idaho", 
        "IL": "Illinois", 
        "IN": "Indiana", 
        "IA": "Iowa", 
        "KS": "Kansas", 
        "KY": "Kentucky", 
        "LA": "Louisiana", 
        "ME": "Maine", 
        "MD": "Maryland", 
        "MA": "Massachusetts", 
        "MI": "Michigan", 
        "MN": "Minnesota", 
        "MS": "Mississippi", 
        "MO": "Missouri", 
        "MT": "Montana", 
        "NE": "Nebraska", 
        "NV": "Nevada", 
        "NH": "NewHampshire", 
        "NJ": "NewJersey", 
        "NM": "NewMexico", 
        "NY": "NewYork", 
        "NC": "NorthCarolina", 
        "ND": "NorthDakota", 
        "OH": "Ohio", 
        "OK": "Oklahoma", 
        "OR": "Oregon", 
        "PA": "Pennsylvania", 
        "RI": "RhodeIsland", 
        "SC": "SouthCarolina", 
        "SD": "SouthDakota", 
        "TN": "Tennessee", 
        "TX": "Texas", 
        "UT": "Utah", 
        "VT": "Vermont", 
        "VA": "Virginia", 
        "WA": "Washington", 
        "WV": "WestVirginia", 
        "WI": "Wisconsin", 
        "WY": "Wyoming"} 
    return names